# Generated by Django 5.2.3 on 2025-06-27 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Books', 'Books'), ('Toys', 'Toys'), ('Sanitary Kits', 'Sanitary Kits')], max_length=50)),
                ('item_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('donated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
